services:
  bambu-spoolman-sync:
    image: ghcr.io/piitaya/bambu-spoolman-sync:beta
    container_name: bambu-spoolman-sync
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
